list: $/moonwalkerz/press/models/broadcast/columns.yaml
modelClass: MoonWalkerz\Press\Models\Broadcast
title: Broadcasts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'moonwalkerz/press/broadcasts/update/:id'
